SELECT U.NAME, U.SURNAME, COUNT(*) AS "NUMBER OF ORDERS"
FROM PRODUCT_ITEM PI
LEFT JOIN USER_ORDER O
      on PI.ORDER_ID = O.ORDER_ID
LEFT JOIN ACME_USER U
      on O.USER_ID = U.ID
WHERE PI.ORDER_ID IS NOT NULL
GROUP BY O.USER_ID
ORDER BY COUNT(*) DESC